site_name: Chay Docs
nav:
  - À propos: about.md
  - Prairie:
      file: index.md
      children:
        - Secunda: secunda.md
        - Tertia: tertia.md
        - Quarta: quarta.md
        - Quinta: quinta.md
        - Sexta: sexta.md
        - Septima: septima.md
        - Octavia: octavia.md
        - Nona: nona.md
theme:
    name: dracula
markdown_extensions:
  - attr_list
  - md_in_html
